version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: course_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: course_enrollment
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3366:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: course_backend
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: course_enrollment
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend: 
    build: ./frontend
    container_name: course_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"